(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(auto-compression-mode t nil (jka-compr))
 '(blink-cursor-delay 0)
 '(blink-cursor-interval 0.4)
 '(buffers-menu-max-size 30)
 '(case-fold-search t)
 '(column-number-mode t)
 '(compilation-scroll-output t)
 '(current-language-environment "UTF-8")
 '(default-input-method "latin-1-prefix")
 '(ecb-compile-window-height 0.2)
 '(ecb-create-layout-file "~/.emacs.d/.ecb-user-layouts.el")
 '(ecb-grep-find-function (quote rgrep))
 '(ecb-layout-name "right-nav")
 '(ecb-layout-window-sizes (quote (("left-analyse" (0.20297029702970298 . 0.33962264150943394) (0.20297029702970298 . 0.20754716981132076) (0.20297029702970298 . 0.20754716981132076) (0.20297029702970298 . 0.22641509433962265)))))
 '(ecb-options-version "2.33beta1")
 '(ecb-primary-secondary-mouse-buttons (quote mouse-1--C-mouse-1))
 '(ecb-process-non-semantic-files nil)
 '(ecb-run-ediff-in-ecb-frame nil)
 '(ecb-tip-of-the-day nil)
 '(ecb-wget-setup (quote ("wget" . other)))
 '(ecb-windows-width 0.2)
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(face-default-stipple "gray3" t)
 '(follow-auto nil)
 '(frame-background-mode nil)
 '(global-font-lock-mode t nil (font-lock))
 '(global-hl-line-mode nil)
 '(global-semantic-idle-scheduler-mode nil nil (semantic-idle))
 '(grep-highlight-matches t)
 '(grep-scroll-output t)
 '(highlight-changes-global-changes-existing-buffers t)
 '(highlight-changes-global-initial-state (quote active))
 '(ibuffer-enable t)
 '(indent-tabs-mode nil)
 '(inhibit-splash-screen t)
 '(make-backup-files nil)
 '(mouse-yank-at-point t)
 '(quack-fontify-style nil)
 '(recentf-exclude (quote ("/tmp/")))
 '(recentf-mode t)
 '(ruby-electric-expand-delimiters-list nil)
 '(safe-local-variable-values (quote ((Package . LISP-UNIT))))
 '(show-paren-mode t)
 '(show-trailing-whitespace t)
 '(slime-autodoc-mode t t)
 '(speedbar-directory-unshown-regexp "^\\(CVS\\|RCS\\|SCCS\\|\\.svn\\|_darcs\\)\\'")
 '(speedbar-show-unknown-files t)
 '(speedbar-use-images nil)
 '(svn-status-hide-unmodified t)
 '(tooltip-delay 1.5)
 '(tooltip-mode t nil (tooltip))
 '(truncate-lines nil)
 '(uniquify-buffer-name-style nil nil (uniquify))
 '(visible-bell t)
 '(whitespace-check-indent-whitespace t)
 '(whitespace-display-in-modeline nil)
 '(whitespace-errbuf "*Messages*")
 '(whitespace-global-mode t)
 '(whitespace-silent t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(whitespace-highlight ((((class color) (background light)) (:background "lightyellow")))))
