(require 'thing-edit)
;@see http://blog.siteshen.com/2011/02/copy-and-paste-in-emacs.html
(define-prefix-command 'thing-edit-map)
(global-set-key (kbd "M-c") 'thing-edit-map)
(define-key 'thing-edit-map (kbd "w") 'thing-paste-word)
(define-key 'thing-edit-map (kbd "l") 'thing-paste-line)
(define-key 'thing-edit-map (kbd "x") 'thing-paste-sexp)
(define-key 'thing-edit-map (kbd "f") 'thing-paste-defun)
(define-key 'thing-edit-map (kbd "s") 'thing-paste-sentence)

(define-key 'thing-edit-map (kbd "M-w") 'thing-copy-word)
(define-key 'thing-edit-map (kbd "M-l") 'thing-copy-line)
(define-key 'thing-edit-map (kbd "M-x") 'thing-copy-sexp)
(define-key 'thing-edit-map (kbd "M-f") 'thing-copy-defun)
(define-key 'thing-edit-map (kbd "M-s") 'thing-copy-sentence)
(provide 'init-thing-edit)
