* Warning
- *If you are absolutely newbie and want to use Emacs immediately, please check the section "Install stable version in easiest way".*
- I'm using [[http://www.vim.org][Vim]] key binding. Please see section *Tips* if you prefer the Emacs key binding.
- People in Mainland China may need [[http://code.google.com/p/goagent/][goagent]] to download packages from ELPA. Run command "http_proxy=http://127.0.0.1:8087 emacs -nw" after starting goagent server (or any proxy server).
- C++/C developers, you need tell Emacs location of header files. You *MUST* see section `clang` now!
- I suggest Windows users using [[http://www.cygwin.com/][Cygwin]] version Emacs to avoid overhead of setting up third party tools. But this configuration is still usable even in  native windows Emacs if you set up environment variable HOME.
- I whitelist packages from [[http://melpa.milkbox.net][melpa]] (melpa-unstable, actually). Modify variable "melpa-include-packages" in init-elpa.el if you prefer some package from it.
- In your bug report, please include details of environment (OS, Emacs version ...) and the full output of `emacs --debug-init`.
- Remove bundled emacs 22 at first *if you are using OS X*!
- If you don't want to use Emacs' own package manager, please extract the package into ~/.emacs.d/site-lisp. There are already samples there.

* General
My first priority is *stable*. So I use fewer cutting-edge packages from [[http://melpa.milkbox.net][melpa]]. If you want to get all the latest package from melpa, search the line containing "(setq package-filter-function nil)" in "init-elpa.el" and *un-comment* it.

Most modern popular programming languages are supported (C/C++/Java/Ruby/Perl/Python/C#/Lua/Javascript ...).

I will provide a updated and stable set up here. But don't count on my explaining usage of every package. You need contact the original developer for tech support. Besides, [[http://www.emacswiki.org/emacs/][EmacsWiki]] has all the tips you need.

A guide for newbies is provided at section *Quick Guide*.

If you need a high level guide on how to become a master. Please check my [[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide][Mastering Emacs in one year]].

* Features
- All key binding and plugins are usable in terminal
- Real time HTML syntax checker enabled (you need install tidy or tidy-html5). I recommend tidy-html5.
- git or subversion is *NOT* needed. You *DONOT* need run 'git submodule update'.
- optimized for cross-platform C++ development with CMake and wxWidgets
- emacs-w3m (console browser)
- eim (Chinese pinyin input method)
- org2blog (post wordpress blog with org-mode)
- make the configuration work on *ALL* platforms (Linux/Cygwin/Mac).
- The configuration work with Emacs version >=24 but still usable with Emacs version 23 (tested with Emacs 23.4.1).
- evil-mode and its plugins (Vim key binding)
- yasnippet and my customized snippets (insert code snippet by typing less keys)

* Install
Download [[https://github.com/redguardtoo/emacs.d/archive/master.zip][this zip file]] and extract its content into ~/.emacs.d. Ensure that the 'init.el' contained in this repo ends up at ~/.emacs.d/init.el and old ~/.emacs *IS REMOVED*.

You *possibly* need run the below command in the terminal at least once to update the content from package repositories:
#+BEGIN_SRC elisp
emacs -nw --batch -l ~/.emacs.d/init.el -f package-refresh-contents
#+END_SRC

*If you cannot download packages from remote repository (for example, you are behind company firewall), don't panic!*

You do have USB stick, right?

Check the section *Install stable version in easiest way* for solutions.

* Quick guide
** Step 1, Learn OS basics
- Know what's environment variable
- Know what's pipe, stdout, stdin
** Step 2, Read official tutorial at least once
Press "C-h t" (C means Ctrl) and start read tutorial.
- Know how to move cursor
- Know how to open help. Press "C-h v" and "C-h f".
** Step 3, Know org-mode basics
[[http://orgmode.org/][Org-mode]] is a for notes-keeping and planning.
Please watch the [[https://www.youtube.com/watch?v=oJTwQvgfgMM][Carsten Dominik's talk]]. It's really simple. The only hot key you need remember is "Tab".
** Step 4, Solve your first *specific* problem
For that specific problem, you can visit [[http://www.emacswiki.org/emacs/][EmacsWiki]] for the solution. Newbies can ask for help on [[http://www.reddit.com/r/emacs/]].
* Directory structure
init.el is main file which include all the other *.el files.

init-elpa define how and what packages will be installed from [[http://elpa.gnu.org][elpa]]/[[http://marmalade-repo.org][marmalade]]/[[http://melpa.milkbox.net][melpa]] by package manager.

The package manager will extract packages into ~/.emacs.d/elpa/.

I also manually download and extract some packages into ~/.emacs.d/site-lisp/. Packages in ~/.emacs.d/site-lisp/ is not visible to Emacs package manager.

My own snippets for [[https://github.com/capitaomorte/yasnippet][Yasnippet]] is in ~/.emacs.d/snippets.

Other directoris do not matter.

* Third party command line tools
These tools are *OPTIONAL*. Your Emacs will NOT crash if they are not installed.

** w3m (web browser in console) 
- needed by `w3m` (w3m is emacs package name written in elisp)
- install through OS package manager
- please note only emacs with GUI can display image

** lua
- required by `flymake-lua`
- install through OS package manager

** aspell (RECOMMENDED) or hunspell, and corresponding dictionary (aspell-en, for example)
- needed by `flyspell`
- hunspell is the alternative of `aspell`. So you need only install either aspell or hunspell.
- install through OS package manager
- I force the dictionary to "en_US" in init-spelling.el. You can modify it in init-spelling.el.

** sbcl (lisp environment)
- needed by lisp `slime`
- install through OS package manager

** tidy (html tidy program) or html5-tidy (RECOMMENDED)
- needed by `web-mode` for real time HTML syntax check
- install through OS package manager
- For html5-tidy, you need [[https://github.com/w3c/tidy-html5/archive/master.zip][download its source code]] and build it manually

** csslint
- install `node.js` through OS package manager, then `sudo npm install -g csslint`

** zip and unzip
- needed by `org-mode` to export org to odt
- install through OS package manager

** jshint (if you use js-mode instead js2-mode)
- install `node.js` through OS package manager, then `sudo npm install -g jshint`
** xsel
- needed by my clipboard command `copy-to-x-clipboard` and `paste-from-x-clipboard` under Linux
- install through OS package manager

** [[http://clang.llvm.org][Clang]]
- needed by `cpputils-cmake`, `company-clang`
- install through OS package manager
- If you use `cpputils-cmake` and `cmake`, `cpputils-cmake` will do all the set up for you. You don't need read next item! But please spend *a few minutes to learn the basics of cmake*! There is a one minute step-by-step-guide in [[https://github.com/redguardtoo/cpputils-cmake][README of cpputils-cmake]] to teach you how to use cmake.
- If you use `company-clang`, add `(setq company-clang-arguments '("-I/example1/dir" "-I/example2/dir"))` into ~/.emacs.d/init.el
** GCC/Make
- needed by `flymake`
- install through OS package manager
** [[https://addons.mozilla.org/en-us/firefox/addon/mozrepl/][MozRepl (Firefox addon)]]
- needed by [[http://www.emacswiki.org/emacs/MozRepl][MozRepl]]
- used by Firefox

** [[http://ctags.sourceforge.net][CTags]]
- it creates tags file for code navigation
- needed by many tags related plugins
- install through OS package manager
- See [[http://blog.binchen.org/?p=1057][How to use ctags in Emacs effectively]] for my guide

** [[http://www.gnu.org/software/global][GNU Global]] 
- needed by `ggtags.el`
- it creates index files for code navigation
- more advanced than ctags, supports references and better performance
- install through OS package manager

** pyflakes
- You need pyflakes for real time python syntax checker like `flymake-python`
- Install pip through OS package manager, then `pip install pyflakes`
- On cygwin you need install `setuptool` in order to install `pip`.

** libreoffice
- Only one executable `soffice` needed when converting odt file into doc (Microsoft Word 97)
- conversion will happen automatically when exporting org-mode to odt
- The conversion command is in variable `org-export-odt-convert-processes`
- Install through OS package manager
** js-beautify
- To beautify javascript code (insert extra space, for example)
- Install pip through OS package manager, then `pip install jsbeautifier`
* OS package manager recommended
- [[https://github.com/cfg/apt-cyg][apt-cyg]] at Cygwin
- [[https://github.com/mxcl/homebrew][homebrew]] at Mac
- any package manager at Linux

* Install stable version in easiest way
You don't need git or network any more. All you need are just two zip files.

Here are the exact steps you need follow:
- Download https://github.com/redguardtoo/emacs.d/archive/v1.0.zip
- Extract its content into empty directory "~/.emacs.d" ("~" means HOME directory). After extraction, there will be a file named "init.el" in "~/.emacs.d"
- Download [[https://github.com/redguardtoo/myelpa/archive/v1.0.zip]]
- Extract the zip somewhere, say "~/myelpa".
- Double check that there is a file named "archive-contents" in the directory "~/myelpa"
- Uncomment below code in ~/.emacs.d/init-elpa.el and start Emacs now!
#+BEGIN_SRC bash
(setq package-archives '(("myelpa" . "~/myelpa/")))
#+END_SRC

That's it. You will never need internet connection in the future. I tested it on *Emacs 24.3 and Emacs 23.4*.

Please note that all your packages are locked. So you *cannot* upgrade package online in the future *unless you comment out above code line again*.

I don't recommend advanced users locking their packages.
* Report bug
Please file bug report at [[https://github.com/redguardtoo/emacs.d]]. Don't send me email!

* Tips
By default EVIL (Vim emulation in Emacs) is used. You can comment out line containing "(require 'init-evil)" in init.el to unload it.

Some package cannot be downloaded automatically because of network problem.

You need manually `M-x list-packages` and install it or just `M-x package-refresh-content` and restart Emacs.

If you use `gnus` for email (Gmail, for example). Check ~/.emacs.d/init-gnus.el which includes my most settings except my private stuff. Here is [[http://blog.binchen.org/?p=403][my Gnus tutorial]].

To toggle Chinese input method (eim, for example), press `C-\` or run command `M-x toggle-input-method`.

* FAQ
As I said, please contact the original developer for help. My answer may be outdated soon.
** Why auto-completion/intellisense does not work?
I assume you use company-mode. Other plugins have similar set up.

At minimum:
- You need install clang
- Make sure your code is syntax correct at the beginning
- assign reasonable value into company-clang-arguments

Here is sample set up in ~/.emacs:
#+begin_src elisp
(setq company-clang-arguments '("-I/home/myname/projs/test-cmake" "-I/home/myname/projs/test-cmake/inc"))
#+end_src

In "friendly" Visual C++, you need do [[http://www.codeproject.com/Tips/588022/Using-Additional-Include-Directories][similar set up]].
** How to use color theme in CLI emacs
#+BEGIN_SRC sh
TERM=xterm-256color emacs -nw
#+END_SRC
** When editing python code, the computer is not responsive
Don't open two Emacs instances to edit python files. This is the bug of anaconda-mode (version 20140605.757).
UPDATE: the bug is fixed after that version.
* My personal custom.el (OPTIONAL)
It's publicized at [[http://blog.binchen.org/?p=430]]. It contains my personal stuff.
* About Emacs23
Emacs23 support will *be dropped* in one year <2015-04-24 Thu>.
Currently Emacs 23 will not support below packages:
- helm
- org-mode and its third party packages
- company-mode
