#!/bin/sh -e

for f in site-lisp/*/.git; do
  echo '***' `dirname $f`
  (cd $f/.. && git pull)
done

for f in site-lisp/*/_darcs; do
  echo '***' `dirname $f`
  (cd $f/.. && darcs pull --all)
done

for f in site-lisp/*/.svn; do
  echo '***' `dirname $f`
  (cd $f/.. && svn up)
done

for f in site-lisp/*/CVS; do
  echo '***' `dirname $f`
  (cd $f/.. && cvs up -dP)
done

echo '***' rinari
(cd site-lisp/rinari && git pull eschulte master)

echo '*** anything'
(cd site-lisp/anything && (for f in anything.el anything-config.el; do curl -o $f "http://www.emacswiki.org/emacs/download/$f"; done))

echo '***' haml
(cd site-lisp/haml && (for f in haml-mode.el sass-mode.el; do curl -o $f "http://github.com/nex3/haml/blob/master/extra/$f?raw=true"; done))

echo '*** paredit'
(cd site-lisp/paredit && curl -o paredit.el http://mumble.net/~campbell/emacs/paredit.el)

echo '***' js-comint
(cd site-lisp/js-comint && curl -o js-comint.el http://downloads.sourceforge.net/js-comint-el/js-comint.el)

echo '***' autocomplete
(cd site-lisp/auto-complete && curl -o auto-complete.el http://www.cx4a.org/pub/auto-complete.el)
(cd site-lisp/auto-complete && curl -o ac-dabbrev.el http://www.emacswiki.org/emacs/download/ac-dabbrev.el)

echo '***' mozrepl
(cd site-lisp/moz-repl && curl -o moz.el 'http://github.com/bard/mozrepl/tree/master/chrome%2Fcontent%2Fmoz.el?raw=true')
