#!/bin/sh -e

function emacswiki_get {
  curl -o $1 "http://www.emacswiki.org/emacs/download/$1"
}

echo "*** Git submodules"
git submodule foreach 'git pull'

for f in site-lisp/*/_darcs; do
  echo '***' `dirname $f`
  (cd $f/.. && darcs pull --all)
done

for f in site-lisp/*/.svn; do
  echo '***' `dirname $f`
  (cd $f/.. && svn up)
done

for f in site-lisp/*/CVS; do
  echo '***' `dirname $f`
  (cd $f/.. && cvs up -dP)
done

echo '*** anything'
(cd site-lisp/anything && (for f in anything.el anything-config.el; do emacswiki_get $f; done))

echo '*** todochiku'
(cd site-lisp/todochiku && emacswiki_get todochiku.el)

echo '***' haml
(cd site-lisp/haml && (for f in haml-mode.el sass-mode.el; do curl -o $f "http://github.com/nex3/haml/blob/master/extra/$f?raw=true"; done))

echo '*** paredit'
(cd site-lisp/paredit && curl -o paredit.el http://mumble.net/~campbell/emacs/paredit.el)

echo '***' js-comint
(cd site-lisp/js-comint && curl -o js-comint.el http://downloads.sourceforge.net/js-comint-el/js-comint.el)

echo '***' mozrepl
(cd site-lisp/moz-repl && curl -o moz.el 'http://github.com/bard/mozrepl/blob/master/chrome/content/moz.el?raw=true')

echo '***' twit
(cd site-lisp/twit && emacswiki_get twit.el)

echo '***' paredit
(cd site-lisp/paredit && curl -o paredit.el http://mumble.net/~campbell/emacs/paredit-beta.el)

echo '***' revive
(cd site-lisp/revive && curl -o revive.el http://www.gentei.org/~yuuji/software/revive.el)

echo '***' color-theme-subdued
(cd site-lisp/color-theme-subdued && curl -o color-theme-subdued.el http://jblevins.org/git/misc.git/plain/color-theme-subdued.el)

echo '***' smooth-scrolling
(cd site-lisp/smooth-scrolling && curl -o smooth-scrolling.el http://adamspiers.org/computing/elisp/smooth-scrolling.el)
