\input texinfo  @c -*-texinfo-*-
@c %**start of header
@setfilename semantic.info
@set TITLE  Semantic Manual
@set AUTHOR Eric M. Ludlam, David Ponce, and Richard Y. Kim
@settitle @value{TITLE}

@c *************************************************************************
@c @ Header
@c *************************************************************************

@c Merge all indexes into a single index for now.
@c We can always separate them later into two or more as needed.
@syncodeindex vr cp
@syncodeindex fn cp
@syncodeindex ky cp
@syncodeindex pg cp
@syncodeindex tp cp

@c @footnotestyle separate
@c @paragraphindent 2
@c @@smallbook
@c %**end of header

@copying
This manual documents Semantic, a new intrastructure for parser
based text analysis for Emacs.

Copyright @copyright{} 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2007 Eric M. Ludlam
Copyright @copyright{} 2001, 2002, 2003, 2005 David Ponce
Copyright @copyright{} 2002, 2003 Richard Y. Kim

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with the
Invariant Sections being list their titles, with the Front-Cover Texts
being list, and with the Back-Cover Texts being list.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License''.
@end quotation
@end copying

@ifinfo
@dircategory Emacs
@direntry
* Semantic: (semantic).	Infrastructure for parser based text analysis.
@end direntry
@end ifinfo

@iftex
@finalout
@end iftex

@c @setchapternewpage odd
@c @setchapternewpage off

@ifinfo
This file documents Semantic.
@emph{Infrastructure for parser based text analysis in Emacs}

Copyright @copyright{} 2002 @value{AUTHOR}
@end ifinfo

@titlepage
@sp 10
@title @value{TITLE}
@author by @value{AUTHOR}
@vskip 0pt plus 1 fill
Copyright @copyright{} 1999, 2000, 2001, 2002, 2003 @value{AUTHOR}
@page
@vskip 0pt plus 1 fill
@insertcopying
@end titlepage
@page

@c MACRO inclusion
@include semanticheader.texi


@c *************************************************************************
@c @ Document
@c *************************************************************************
@contents

@node top
@top @value{TITLE}

@semantic{} is a program for Emacs which includes, at its core, a
lexer, and two compiler compilers (bovinator and wisent).  Additional
tools include, support for imenu, speedbar, whichfunc, eldoc,
hippie-expand, and several other build in tools.

The core utility is the parser infrastructure which allows different
types of parsers to be linked into the system.  Two build in parsers
include the ``bovine'' parser, and the ``wisent'' parser.

To send bug reports, or participate in discussions about semantic,
use the mailing list cedet-semantic@@sourceforge.net via the URL:
@url{http://lists.sourceforge.net/lists/listinfo/cedet-semantic}

@menu
* Overview::                    
* Installation/Basic Configuration::                
* Semantic manuals::            
* Semantic Internals::          
* Glossary::                    
* GNU Free Documentation License::  
* Index::                       
@end menu

@node Overview
@chapter Overview

@include overview.texi

@node Installation/Basic Configuration
@chapter Installation and Basic Configuration

@include installation.texi

@node Semantic manuals
@chapter Semantic manuals

To know how to use applications enabled by @semantic{},
@inforef{top, the User's Guide, semantic-user}.

If you are an application developer and need to know the functions and
concepts, 
@inforef{top, the Application Development Manual, semantic-appdev}.

To support a new language,
@inforef{top, the Language Support Developer's Guide, semantic-langdev}.

To use the grammar writing environment, and write in the rule based
language, 
@inforef{top, the Grammar Framework Manual, grammar-fw}.

For details on the original @semantic{} @acronym{LL} parser,
@inforef{top, the Bovine Parser Manual, bovine}.
 
For details on the Bison-like @acronym{LALR} parser,
@inforef{top, the Wisent Parser Manual, wisent}.

@node Semantic Internals
@chapter Semantic Internals

@include internals.texi

@node Glossary
@appendix Glossary

@include glossary.texi

@node GNU Free Documentation License
@appendix GNU Free Documentation License

@include fdl.texi

@node Index
@unnumbered Index
@printindex cp

@iftex
@contents
@summarycontents
@end iftex

@bye

@c Following comments are for the benefit of ispell.

@c LocalWords: alist API APIs arg argc args argv asis assoc autoload Wisent
@c LocalWords: backquote bnf bovinate bovinates LALR
@c LocalWords: bovinating bovination bovinator bucketize
@c LocalWords: cb cdr charquote checkcache cindex CLOS
@c LocalWords: concat concocting const constantness ctxt Decl defcustom
@c LocalWords: deffn deffnx defun defvar destructor's dfn diff dir
@c LocalWords: doc docstring EDE EIEIO elisp emacsman emph enum
@c LocalWords: eq Exp EXPANDFULL expresssion fn foo func funcall
@c LocalWords: ia ids iff ifinfo imenu imenus init int isearch itemx java kbd
@c LocalWords: keymap keywordtable lang languagemode lexer lexing Ludlam
@c LocalWords: menubar metaparent metaparents min minibuffer Misc mode's
@c LocalWords: multitable NAvigaTOR noindent nomedian nonterm noselect
@c LocalWords: nosnarf obarray OLE OO outputfile paren parsetable POINT's
@c LocalWords: popup positionalonly positiononly positionormarker pre
@c LocalWords: printf printindex Programmatically pt punctuations quotemode
@c LocalWords: ref regex regexp Regexps reparse resetfile samp sb
@c LocalWords: scopestart SEmantic semanticdb setfilename setq
@c LocalWords: settitle setupfunction sexp sp SPC speedbar speedbar's
@c LocalWords: streamorbuffer struct subalist submenu submenus
@c LocalWords: subsubsection sw sym texi texinfo titlefont titlepage
@c LocalWords: tok TOKEN's toplevel typemodifiers uml unset untar
@c LocalWords: uref usedb var vskip xref yak
