#!/bin/sh -e

if [ -d emacs-rails-svn/.svn ]; then
  exec svn up emacs-rails-svn
fi

if [ -d emacs-rails-svn ]; then
  mv emacs-rails-svn emacs-rails-svn-orig
fi
svn co http://emacs-rails.rubyforge.org/svn/trunk emacs-rails-svn
rm -rf emacs-rails-svn-orig
