#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/ibus-el

# Written by Jim Van Zandt <jrv@debian.org>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=ibus-el
PKGSNAME=ibus

case $FLAVOR in
    emacs|emacs21|emacs20|emacs19|mule2|*xemacs*)
    exit 0
    ;;
    *)
    EMACSEN=$FLAVOR
    ;;
esac

echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}

#FLAVORTEST=`echo $FLAVOR | cut -c-6`
#if [ ${FLAVORTEST} = xemacs ] ; then
#    SITEFLAG="-no-site-file"
#else
#    SITEFLAG="--no-site-file"
#fi
#FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"
FLAGS="-no-site-file -q -batch -l path.el -f batch-byte-compile"

ELDIR=/usr/share/emacs/site-lisp/${PKGSNAME}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PKGSNAME}

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
FILES=`echo *.el`
cd ${ELCDIR}
for i in ${FILES}; do
    ln -sf ${ELDIR}/$i .
done

cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
EOF
${FLAVOR} ${FLAGS} ${FILES}
rm -f path.el

exit 0
