;;; org-version.el --- autogenerated file, do not edit
;;
;;; Code:
;;;###autoload
(defun org-release ()
  "The release version of Org.
Inserted by installing Org mode or when a release is made."
   (let ((org-release "9.1.2"))
     org-release))
;;;###autoload
(defun org-git-version ()
  "The Git version of org-mode.
Inserted by installing Org or when a release is made."
   (let ((org-git-version "9.1.2-32-g271e58-elpaplus"))
     org-git-version))
;;;###autoload
(defvar org-odt-data-dir "/usr/share/emacs/etc/org"
  "The location of ODT styles.")

(provide 'org-version)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; coding: utf-8
;; End:
;;; org-version.el ends here
