@c -*-texinfo-*-
@c
@c $Id: d-dataobj.texi,v 1.2 1996/11/18 00:00:46 zappo Exp $
@c

@c The next line is for the back-search to see what node this one
@c resides in.

@c @node Data Object,
@c @chapter Data Object

@c This command is a convenience to help rebuild this file.  Use C-x C-e
@c on the expression below to rebuild the entire widget index (but only
@c after loading in the dialog tool.)

@c (eieiodoc-class data-object "do")

@menu
* data-object ::
@end menu


@node data-object,  ,  , Data Object
@comment  node-name,  next,  previous,  up
@section data-object
@doindex data-object

@table @asis
@item Inheritance Tree:
@table @code
@item data-object
No children
@end table
@end table

  This defines a @code{data-object} which is used for all widgets
maintaining some value.  For example, a @code{widget-label} @xref{widget-label} displays a
string or number, and a @code{widget-scrollbar} @xref{widget-scrollbar} edits a number.  These
widgets will use data-object to store their data.

@table @asis
@item Private Slots:

@table @code
@item :value
Default Value: @code{nil}

Lisp object which represents the data this object maintains.
@refill

@item :reference
Default Value: @code{nil}

List of objects looking at me.  The method @dfn{update-symbol} is called
for each member of @code{reference} whenever @code{value} is modified.
@refill

@end table

@end table
