# Copyright (C) 1995,96,98,99 Eric M. Ludlam
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can either send email to this
# program's author (see below) or write to:
#
#              The Free Software Foundation, Inc.
#              675 Mass Ave.
#              Cambridge, MA 02139, USA.
#
# Please send bug reports, etc. to zappo@gnu.org
#
# $Id: Makefile.old,v 1.5 1999/03/09 14:14:42 zappo Exp $


VERSION=$(shell grep "Version: " eieio.el | cut -d" " -f3)

LISP=eieio-comp.el eieio-custom.el eieio-doc.el eieio-opt.el eieio.el

LISPE=tree.el call-tree.el chart.el dbif-browse.el dbif-edit.el dbif.el psql.el

TEXINFO=eieio.texi

STUFF=Makefile eieiocomp.el

# dialog code is not distributed.
DIALOG=dialog-mode.el dialog-tree.el dlg-class.el dlg-config.el \
	e-config.el ecfg-menu.el widget-d.el widget-i.el

all: eieio.info
	emacs -batch -l eieiocomp.el

eieio.info: eieio.texi
	makeinfo eieio.texi

dist: $(LISP) $(TEXINFO) $(STUFF)
	mkdir eieio-$(VERSION)
	cp $(LISP) $(LISPE) $(TEXINFO) $(STUFF) eieio-$(VERSION)
	tar -cvzf eieio-$(VERSION).tar.gz eieio-$(VERSION)
	rm -rf eieio-$(VERSION)

#end